### PR TITLE
Added support for bounds specified in raw units

### LINKED ISSUE #19: Add raw bounds to dataTOSTxxx() functions
hi @Lakens,

i was going to add a 'Bounds type' option to the `dataTOSTxxx()` and jamovi analyses, like so:

screen shot 2017-11-06 at 14 40 09

sound good?

jamovi/jamovi#358

cheers

### PR DESCRIPTION
**Pull request by jonathon-love**
closes #19

### CODE REVIEW

**Comment by Lakens** [comment]
Excellent stuff - thanks!

**Comment by jonathon-love** [comment]
did you want to push a new version to CRAN soon?

before you do, increment the version in `jamovi/0000.yaml` to be the same as in the `DESCRIPTION` file.

cheers

**Comment by Lakens** [comment]
Hi, we are going for a 0.3 release - I've updated the version number in the yaml file. We added some good stuff (more options as output in the power functions, option not to show the plot (for simulations). We also added a proportions equivalence test (which should eventually end up in Jamovi as well!). But we want to add some proportion tests (for odds ratios) and the 1.0 release should include non-parametric tests (requested feature).

**Comment by pederisager** [comment]
Hello Jonathan, excellent work!

I realized that for simulation purposes, being able to turn off printed
output in addition to the plots might be the better solution, but not sure
if I am able to implement in time for CRAN push. Do we have a deadline for
0.3 release to CRAN?

2017-11-09 9:28 GMT+01:00 Daniel Lakens <notifications@github.com>:

**Comment by jonathon-love** [comment]
hey, nah, no rush.

incidentally, i don't think you want to 'turn off' the printed output. what you'd be better off doing is overriding the print function of the results objects that the `TOSTxxx()` functions return (but you possibly/probably already realise this).

this way they'll still generate images, etc. when used interactively, but won't when used in a loop/simulation.

**Comment by Lakens** [comment]
Yes, we just realized the current 'print' part in the TOST functions might not have been best practice, it can be hidden using:

invisible(capture.output(out.x<-powerTOSTpaired(alpha=0.05,N=96,statistical_power=0.8)))
out.x

So for simulations, it should be fine for now.

**Pull request merged**
